name: 🥺 No Response

on:
  issue_comment:
    types: [created]
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: "5 * * * *"

jobs:
  noResponse:
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest

    steps:
        uses: lee-dohm/no-response@v0.5.0
        with:
          closeComment: >
            This issue has been automatically closed because we haven't received a
            response from the original author 🙈. This automation helps keep the issue
          daysUntilClose: 10
          responseRequiredLabel: needs-response
